name: Comment on PRs

on:
  pull_request_target:
    branches:    
      - main
    paths:
      - 'extensions/*/*.json'

jobs:
  comment:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
          echo "$JAVA_HOME_17_X64/bin" >> $GITHUB_PATH

      - run: |
          curl -sLO https://download.clojure.org/install/linux-install-1.11.1.1113.sh
          chmod +x linux-install-1.11.1.1113.sh
          sudo ./linux-install-1.11.1.1113.sh

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: clojure -P
        name: Fetch deps

      - name: Add comment to PR
        env:
          PR: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./script/comment.sh --pr $PR --token $GITHUB_TOKEN
